import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard/BlogCard";
import SideBar from "../components/SideBar";
import Footer from "../components/Footer";

const graphcms = new GraphQLClient(
  "https://api-sa-east-1.graphcms.com/v2/cl45lk6e90i0201z3ckfz8f0t/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        publishedAt
        createdBy {
          id
        }
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {posts.map((post) => (
            <BlogCard
              title={post.title}
              author={post.author}
              coverPhoto={post.coverPhoto}
              key={post.id}
              datePublished={post.datePublished}
              slug={post.slug}
            />
          ))}
        </main>
      </div>
      <SideBar />
      <Footer />
    </>
  );
}
